## Module list config file
---
name: sitemap.xml Link List
vendor: nkorg
key: sitemaplinklist
author: Stefan
link: https://nobody-knows.org/fanpress3/
version: 3.4.0
sysversion: 3.4.0
description: "Module for use with sitemap.xml files to fill link list in TinyMCE or Link auto completion in HTML-Editor with internal link."
