## Module list config file
---
name: FanPress CM Classic Importer
vendor: nkorg
key: classicimporter
author: imagine
link: https://nobody-knows.org/
version: 3.4.0
sysversion: 3.0.0
description: "Import module for FanPress CM 2.5"