## Module list config file
---
name: RSS Importer
vendor: nkorg
key: rssimport
author: imagine
link: https://nobody-knows.org
version: 3.5.2
sysversion: 3.5.0
description: "Importer for article feeds based on RSS2 or Atom feeds."
