## Module list config file
---
name: FanPress CM Integration
vendor: nkorg
key: integration
author: Stefan
link: https://nobody-knows.org/fanpress3
version: 3.4.0
sysversion: 3.4.0
description: "Helper module for integration of FanPress CM into your website."
