## Module list config file
---
name: Language Editor
vendor: nkorg
key: langeditor
author: Stefan
link: https://nobody-knows.org
version: 3.4.0
sysversion: 3.4.0
description: "The "Language editor" module offers you an way to easily edit language files included in FanPress CM as is and installed modules."
