## Module list config file
---
name: Inactivity Manager
vendor: nkorg
key: inactivity_manager
author: Stefan
link: http://nobody-knows.org/
version: 3.2.0
sysversion: 3.2.0
description: "The Inactivity Manager module allows you to manage and display of various messages, in case of temporary inactivity or increased response time of your website, for example when you're on vacation. The module also allows you to disable certain features of your FanPress CM system like posting new comments."
