## Module list config file
---
name: Tweet Extender
vendor: nkorg
key: tweetextender
author: Stefan
link: https://nobody-knows.org/
version: 3.5.0
sysversion: 3.5.0
description: "The Tweet Extender allows you to modify posts send to twitter when the connection and sending on creation/ updating is enabled."
