## Module list config file
---
name: Tweet Extender
vendor: nkorg
key: tweetextender
author: Stefan
link: http://nobody-knows.org/
version: 3.0.1
sysversion: 3.0.0
description: "The Tweet Extender allows you to modify posts send to twitter when the connection and sending on creation/ updating is enabled."
